### ISSUE TITLE
Adding systems 

### ISSUE THREAD

**Issue by wyvernmix** [RetroHursty69/es-theme-magazinemadness#6]
Just to let you know your theme works great with the steamdeck. Would it be possible to get switch PS3 and 3ds added if possible? I know it's technically for the pi but this works great on the steamdeck. 

Thank you again for your wonderful work

**Comment by RetroHursty69** [comment]
Hi

That is good to know thank you. Pretty cool device, wish I could afford one.
I have a small issue with that theme as I have lost the template file for the video view.

I was wondering if you would consider switching over to magazinemadness2?
https://github.com/RetroHursty69/es-theme-magazinemadness2 <https://github.com/RetroHursty69/es-theme-magazinemadness2>

I have the ability it update that one. I just looked and it already has 3ds. I would only need to add PS3.
Let me know and I will try and add PS3 in the next few days if you still want it.

Cheers
Hursty

**Comment by wyvernmix** [comment]
I've just discovered it and have moved over to it yes it needs PS3 and Nintendo switch if you could add those to magazine 2 that's would be amazing thank you so much you legend

**Comment by RetroHursty69** [comment]
Hi

OK leave it with me, I should be able to do that. Busy atm, but will look at doing this over the next week.

Cheers
Hursty

**Comment by RetroHursty69** [comment]
Hi. I have added ’switch’ and ‘ps3’ to magazinemadness2.

Cheers
Hursty

**Comment by wyvernmix** [comment]
I have tested it out and it works an absolute treat thank you ever so much. Could you please include these systems on your new themes so us steam deckers can enjoy your great themes. Thank you again ☺️
